# Generated by Django 5.0.4 on 2024-05-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='title',
        ),
    ]
