# Generated by Django 5.0.4 on 2024-08-06 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_quizquestion_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='answer',
            field=models.CharField(default='answer', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quizzes.quiz'),
        ),
    ]
